// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7WLjZPbyqD5QlyZENJQ1wlHnYdUnI5bE',
    appId: '1:278885378213:web:169d51fd960b018946454c',
    messagingSenderId: '278885378213',
    projectId: 'fir-register-641d0',
    authDomain: 'fir-register-641d0.firebaseapp.com',
    storageBucket: 'fir-register-641d0.appspot.com',
    measurementId: 'G-2BM7T9YGHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlN83faCd4oUFgOBsFl-JqE_hbv8Swyko',
    appId: '1:278885378213:android:cceed2d63927c03346454c',
    messagingSenderId: '278885378213',
    projectId: 'fir-register-641d0',
    storageBucket: 'fir-register-641d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6xTX_A7NfqfqSV5uNvRarQObRxoRYwcs',
    appId: '1:278885378213:ios:dcccf9ba165b74c546454c',
    messagingSenderId: '278885378213',
    projectId: 'fir-register-641d0',
    storageBucket: 'fir-register-641d0.appspot.com',
    iosBundleId: 'com.example.myNewProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6xTX_A7NfqfqSV5uNvRarQObRxoRYwcs',
    appId: '1:278885378213:ios:02332c8c3963ceb746454c',
    messagingSenderId: '278885378213',
    projectId: 'fir-register-641d0',
    storageBucket: 'fir-register-641d0.appspot.com',
    iosBundleId: 'com.example.myNewProject.RunnerTests',
  );
}
